// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AB_FastTravelByItem","status":true,"description":"アイテムによるファストトラベルシステム","parameters":{"FastTravelCommandName":"ファストトラベル","FastTravelCategoryName":"[\"街\",\"ダンジョン\",\"その他\"]","FastTravelCategory":"[\"town\",\"dungeon\",\"other\"]","FastTravelEnableSwitch":"2","FastTravelConfirmMessage":"この場所へ飛びますか？","FastTravelConfirmYesNo":"[\"する\",\"しない\"]"}},
{"name":"AB_QuestSystemByItem","status":true,"description":"アイテムによるクエストシステム","parameters":{"QuestCommandName":"クエスト","QuestCategoryName":"[\"メインストーリー\",\"サブイベント\",\"その他\"]","QuestCategory":"[\"main_story\",\"sub_event\",\"other\"]","QuestPhaseText":"[\"未受注\",\"受注\",\"成功\",\"失敗\",\"消滅\"]","QuestPhaseTextColor":"[\"1\",\"2\",\"4\",\"3\",\"7\"]","QuestPhaseIconIndex":"[\"12\",\"13\",\"29\",\"30\",\"31\"]","QuestPhaseSort":"[\"2\",\"1\",\"3\",\"4\",\"5\"]","QuestWarpSwitch":"2","QuestWarpOccurrenceConfirmMessage":"受注地点の近くにワープしますか？","QuestWarpOccurrenceConfirmYesNo":"[\"ワープする\",\"ワープしない\"]","QuestWarpReceiveConfirmMessage":"目標地点の近くにワープしますか？","QuestWarpReceiveConfirmYesNo":"[\"ワープする\",\"ワープしない\"]"}},
{"name":"AB_Navigation","status":true,"description":"簡易ナビゲーションシステム","parameters":{"NaviEnableSwitch":"7","NaviMapIdVarId":"15","NaviMapXVarId":"16","NaviMapYVarId":"17","NaviFstTrvlItemIdVarId":"18","NaviIconIndex":"95","NaviIconOpacity":"192","NaviIconAdjustX":"8","NaviIconAdjustY":"8","TransferEventListLength":"10","DestinationMessage":"次の目的地：","CannotNaviMessage":"※遠すぎてナビゲーションできません。"}}
];
